"""Generate docs/COVERAGE.md from the registry + pinned ruleset.

Single source of truth for the 46-KSI coverage table. Run:
    python tools/gen_coverage_doc.py            # write
    python tools/gen_coverage_doc.py --check    # verify in sync (CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from fedramp_ksi.ksi import load_all  # noqa: E402
from fedramp_ksi.model import AuthClass, Disposition  # noqa: E402
from fedramp_ksi.registry import all_entries, disposition_counts, has_evaluator  # noqa: E402
from fedramp_ksi.ruleset import load_ruleset  # noqa: E402

DOC = Path(__file__).resolve().parents[1] / "docs" / "COVERAGE.md"


def _disp_label(entry) -> str:
    base = entry.disposition.value
    c = entry.disposition_for(AuthClass.C).value
    return f"{base} → {c} @C" if c != base else base


def render() -> str:
    load_all()
    rs = load_ruleset()
    base = disposition_counts(AuthClass.A)
    cls_c = disposition_counts(AuthClass.C)
    lines = [
        "# KSI Coverage",
        "",
        f"Ruleset **{rs.version}** (sha256 `{rs.sha256[:16]}…`) — **{len(all_entries())} KSIs / "
        "10 themes**. This file is generated by `tools/gen_coverage_doc.py`; do not edit by hand.",
        "",
        "## Disposition totals",
        "",
        "| Class | enforce | advisory | manual |",
        "|---|---|---|---|",
        f"| A/B | {base[Disposition.ENFORCE]} | {base[Disposition.ADVISORY]} | {base[Disposition.MANUAL]} |",
        f"| C | {cls_c[Disposition.ENFORCE]} | {cls_c[Disposition.ADVISORY]} | {cls_c[Disposition.MANUAL]} |",
        "",
        "`enforce` can block the build · `advisory` warns (PARTIAL) · `manual` is recorded MANUAL "
        "with an external evidence pointer. Three KSIs (CNA-EIS, MLA-ALA, SVC-VCM) shift "
        "advisory→enforce at Class C.",
        "",
        "## The 46 KSIs",
        "",
        "| KSI | Name | Disposition | Impl? | NIST 800-53 |",
        "|---|---|---|---|---|",
    ]
    for e in sorted(all_entries(), key=lambda x: x.ksi_id):
        d = rs.get(e.ksi_id)
        impl = (
            "✅"
            if has_evaluator(e.ksi_id)
            else ("—" if e.disposition is Disposition.MANUAL else "▫️")
        )
        controls = ", ".join(d.controls) if d.controls else "—"
        lines.append(f"| `{e.ksi_id}` | {d.name} | {_disp_label(e)} | {impl} | {controls} |")
    lines += [
        "",
        "**Impl?** ✅ = evaluator implemented · ▫️ = enforce/advisory not yet implemented "
        "(reports N/A) · — = manual (no IaC control).",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = DOC.read_text(encoding="utf-8") if DOC.is_file() else ""
        if current != content:
            print("docs/COVERAGE.md is out of date; run: python tools/gen_coverage_doc.py")
            return 1
        print("docs/COVERAGE.md is in sync.")
        return 0
    DOC.write_text(content, encoding="utf-8")
    print(f"wrote {DOC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
